In [2]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

from sklearn.linear_model import LinearRegression

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [3]:
df = pd.read_csv("../data/raw/datafile (1).csv")

df.columns = [
    "Crop",
    "State",
    "Cultivation_Cost_A2_FL",
    "Cultivation_Cost_C2",
    "Production_Cost",
    "Yield"
]

df.head()

,Crop,State,Cultivation_Cost_A2_FL,Cultivation_Cost_C2,Production_Cost,Yield
0,ARHAR,Uttar Pradesh,9794.05,23076.74,1941.55,9.83
1,ARHAR,Karnataka,10593.15,16528.68,2172.46,7.47
2,ARHAR,Gujarat,13468.82,19551.90,1898.30,9.59
3,ARHAR,Andhra Pradesh,17051.66,24171.65,3670.54,6.42
4,ARHAR,Maharashtra,17130.55,25270.26,2775.80,8.72

In [4]:
crop_encoder = LabelEncoder()
state_encoder = LabelEncoder()

df["Crop"] = crop_encoder.fit_transform(df["Crop"])
df["State"] = state_encoder.fit_transform(df["State"])

df.head()

,Crop,State,Cultivation_Cost_A2_FL,Cultivation_Cost_C2,Production_Cost,Yield
0,0,11,9794.05,23076.74,1941.55,9.83
1,0,4,10593.15,16528.68,2172.46,7.47
2,0,2,13468.82,19551.90,1898.30,9.59
3,0,0,17051.66,24171.65,3670.54,6.42
4,0,6,17130.55,25270.26,2775.80,8.72

In [5]:
X = df.drop("Yield", axis=1)

y = df["Yield"]

print(X.head())
print(y.head())

   Crop  State  Cultivation_Cost_A2_FL  Cultivation_Cost_C2  Production_Cost
0     0     11                 9794.05             23076.74          1941.55
1     0      4                10593.15             16528.68          2172.46
2     0      2                13468.82             19551.90          1898.30
3     0      0                17051.66             24171.65          3670.54
4     0      6                17130.55             25270.26          2775.80
0    9.83
1    7.47
2    9.59
3    6.42
4    8.72
Name: Yield, dtype: float64

In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training Data:", X_train.shape)
print("Testing Data:", X_test.shape)

Training Data: (39, 5)
Testing Data: (10, 5)

In [7]:
model = LinearRegression()

model.fit(X_train, y_train)

print("Model trained successfully!")

Model trained successfully!

In [8]:
y_pred = model.predict(X_test)

print(y_pred)

[ -66.1719653    64.79065914  160.6695458   726.17543995   61.22183052
 -221.28304084 -115.58228362 -140.24469865   80.26912671   63.96788444]

In [9]:
mae = mean_absolute_error(y_test, y_pred)

mse = mean_squared_error(y_test, y_pred)

r2 = r2_score(y_test, y_pred)

print("Mean Absolute Error:", mae)

print("Mean Squared Error:", mse)

print("R2 Score:", r2)

Mean Absolute Error: 116.75955950654824
Mean Squared Error: 19876.701474456746
R2 Score: 0.7799731184806001

In [10]:
from sklearn.tree import DecisionTreeRegressor

In [11]:
dt_model = DecisionTreeRegressor(random_state=42)

dt_model.fit(X_train, y_train)

dt_pred = dt_model.predict(X_test)

print("Decision Tree Model Trained Successfully!")

Decision Tree Model Trained Successfully!

In [12]:
dt_mae = mean_absolute_error(y_test, dt_pred)
dt_mse = mean_squared_error(y_test, dt_pred)
dt_r2 = r2_score(y_test, dt_pred)

print("Decision Tree Results")
print("----------------------")
print("MAE :", dt_mae)
print("MSE :", dt_mse)
print("R² :", dt_r2)

Decision Tree Results
----------------------
MAE : 60.935
MSE : 32128.039230000013
R² : 0.6443558660779731

In [13]:
comparison = pd.DataFrame({
    "Model": ["Linear Regression", "Decision Tree"],
    "MAE": [mae, dt_mae],
    "MSE": [mse, dt_mse],
    "R2 Score": [r2, dt_r2]
})

comparison

               Model        MAE           MSE  R2 Score
0  Linear Regression  116.75956  19876.701474  0.779973
1      Decision Tree   60.93500  32128.039230  0.644356